version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src

  test:
    image: node:20-alpine
    working_dir: /app
    command: npm run test
    volumes:
      - .:/app

  format:
    image: node:20-alpine
    working_dir: /app
    command: npm run format
    volumes:
      - .:/app

  lint:
    image: node:20-alpine
    working_dir: /app
    command: npm run lint
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  dev:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

